# Travaux Pratiques Intelligence Artificielle: Lab2

Neural Networks avec Pytorch 🤖 🙌.

## Objectifs du TP:

> **Se Familiariser avec Pytorch** 

> **Comprendre le processus d'apprentissage d'un réseau de neurones**

> **Créer un réseau de neurones (feed-forward multilayers NN) avec Pytorch**



<br></br>
_Besoin d'aide? Laisser moi un Commentaire sur Teams_

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## A. Introduction à Pytorch

<br> Pytorch est une librairie open source Python, developpée par AI Research lab (FAIR) de Facebook et publiée en ligne en Sept. 2016. Elle permet d'effectuer les calculs tensoriels nécessaires notamment pour l'apprentissage profond (deep learning).   

Pytorch permet une implémentation et un apprentissage facile des réseaux de neurones (NN). Elle est très proche de la syntaxe de Python, d'ailleurs il est même possible d'intégrer des blocs if else dans un code NN. Elle a une riche communauté et une documentation actualisée (comparée à tensorflow). D'autant plus qu'elle est très utilisée par les chercheurs, ce qui garantie l'implémentation des nouveaux modèles sur Pytorch.

Vous pouvez installer Pytorch à partir d'un terminal ou au niveau de ce jupyter en exécutant la cellule ci-dessous. 

**N.B.** Si vous avez des inconsistences au niveau de l'installation, pensez à créer un environnement spécifique pour ce TP.

<br>

<br> 

Afin de mener à bien les implémentations des NN, Pytorch fournit l'objet **Tensor**. Un tensor sur Pytorch a les mêmes fonctions et syntaxe qu'un numpy array mais est optimisé pour GPU. D'autant plus que son backend C++ permet à Pytorch d'être beaucoup plus performante et rapide que numpy. 
<br>

In [1]:
# Importer torch
import torch
print(torch.__version__)

1.7.0


In [59]:
# créer une matrice identité de taille 4x4
eye4 = torch.eye(4)
print(eye4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [71]:
# Créer un tensor avec des valeurs aléatoires d'une taille de votre choix
x = torch.rand(4,3)
print(x)

tensor([[0.5776, 0.7423, 0.0033],
        [0.0299, 0.5667, 0.3081],
        [0.6258, 0.8117, 0.7609],
        [0.8840, 0.2980, 0.3390]])


In [72]:
# Changer la forme de votre tensor 
x.view(3,4)

tensor([[0.5776, 0.7423, 0.0033, 0.0299],
        [0.5667, 0.3081, 0.6258, 0.8117],
        [0.7609, 0.8840, 0.2980, 0.3390]])

In [73]:
# Afficher la taille, la forme,
x.size()

torch.Size([4, 3])

In [74]:
# et le type des éléments de votre tensor
x.type()

'torch.FloatTensor'

In [75]:
xt = torch.transpose(x, 0, 1)

In [76]:
# Ajouter une constante fixe à l'ensemble des éléments du tensor
torch.add(x, 20)

tensor([[20.5776, 20.7423, 20.0033],
        [20.0299, 20.5667, 20.3081],
        [20.6258, 20.8117, 20.7609],
        [20.8840, 20.2980, 20.3390]])

In [77]:
# Multiplier votre tensor par sa transposé (multiplication matricielle, pas element-wise)
torch.mm(x,xt)

tensor([[0.8846, 0.4389, 0.9665, 0.7330],
        [0.4389, 0.4170, 0.7131, 0.2997],
        [0.9665, 0.7131, 1.6294, 1.0530],
        [0.7330, 0.2997, 1.0530, 0.9852]])

In [85]:
# Avec quelques exemples, montrer que la selection d'éléments des tensors se fait de la même manière que sur NumPy 
print(x[1][1], x[3][2])

tensor(0.5667) tensor(0.3390)


<br> 

Une fonctionnalité très utile de Pytorch, est la possibilité d'échanger les tensors facilement avec NumPy.  



In [86]:
# Importer numpy
import numpy as np

In [87]:
# Créer une matrice numpy avec des valeurs aléatoires
a = np.random.rand(3,2)
a

array([[0.69912364, 0.29596159],
       [0.50143137, 0.62314591],
       [0.16017007, 0.69218149]])

In [88]:
# Créer un tensor Pytorch à base de cette matrice np
b = torch.from_numpy(a)
b

tensor([[0.6991, 0.2960],
        [0.5014, 0.6231],
        [0.1602, 0.6922]], dtype=torch.float64)

In [89]:
# Convertir à nouveau ce tensor en un numpy array
c = b.numpy()
c

array([[0.69912364, 0.29596159],
       [0.50143137, 0.62314591],
       [0.16017007, 0.69218149]])

<br> Pytorch, comme numpy, offre une fonctionnalité qu'on appelle **broadcasting**. Elle permet d'exécuter des opérations entre des tensors (resp. arrays) qui n'ont pas la même forme, comme l'illustre la figure suivante:

<img src="resources/broadcasting.png" >

Pytorch assouplie la contrainte de forme mais ne la supprime pas totalement. Il est primordiale d'obéir les règles pour effectuer des oprérations entre deux tensors Pytorch:
1. Deux tensors de même rang sont compatibles (broadcastable) si, pour chaque axe, soit les tailles sont égales, soit l’une d’elles est exactement égale à 1. P.ex. (5, 3) et (1, 3) sont des formats broadcastable, (5, 3) et (5, 1) également, mais (5, 3) et (3, 1) ne le sont pas.
2. Si un tensor a un axe de taille 1, le tensor sera dupliqué à la volée autant de fois que nécessaire selon cet axe pour atteindre la taille de l’autre tensor le long de cet axe. P.ex. un tensor (2, 1, 3) pourra être transformé en tensor (2, 5, 3) en le dupliquant 5 fois le long du 2e axe (axis=1).
3. La taille selon chaque axe après broadcast est égale au maximum de toutes les tailles d’entrée le long de cet axe. P.ex. (5, 3, 1) × (1, 3, 4) → (5, 3, 4).
4. Si un des tensors a un rang (ndim) inférieur à l’autre, alors sa forme (shape) est précédée d’autant de 1 que nécessaire pour atteindre le même rang. P.ex. (5, 3, 1) × (4,) = (5, 3, 1) × (1, 1, 4) → (5, 3, 4).

Pour plus d'informations sur le broadcasting, vous pouvez aller sur le lien: http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc

In [40]:
# Illustrer le broadcasting par un exemple
x = torch.rand(4,3)
y = torch.rand(4,1)
z = x + y
print(x)
print(y)
print(z)

tensor([[0.9146, 0.5507, 0.2223],
        [0.2998, 0.7492, 0.9478],
        [0.3621, 0.1632, 0.8242],
        [0.8251, 0.5894, 0.7851]])
tensor([[0.8841],
        [0.5645],
        [0.9412],
        [0.3639]])
tensor([[1.7987, 1.4348, 1.1063],
        [0.8643, 1.3138, 1.5123],
        [1.3033, 1.1044, 1.7655],
        [1.1891, 0.9533, 1.1490]])


<br> L'unes des fonctionnalités les plus prisée de Pytorch est qu'il permet de calculer d'une manière très facile les gradients des tensors, ce qui est très utile pour appliquer les algorithmes d'optimisation par descente de gradient. Pour cela, PyTorch utilise la bibliothèque autograd qui permet de garder une trace de l'orgine des tensors (leurs tensors parents, les opérations effectuées) et fournir automatiquement la chaîne des dérivées de ces opérations en fonction de leur input. Pytorch fournit donc le gradient d'une expression en fonction de ses paramètres en input automatiquement. 

In [104]:
# Créer un tensor x dont la fonctionalité de gradient est activée
x = torch.tensor([[1., -1., 1., 1.],[1., -1., 1., 1.]] )
x.requires_grad_(True)

tensor([[ 1., -1.,  1.,  1.],
        [ 1., -1.,  1.,  1.]], requires_grad=True)

In [105]:
# Créer un nouveau tensor y, résultat d'une opération linéaire sur le tensor x. L'attribut grad_fn trace l'opération effectuée 
y = x * 0.5
print(y)
print(y.grad_fn)

tensor([[ 0.5000, -0.5000,  0.5000,  0.5000],
        [ 0.5000, -0.5000,  0.5000,  0.5000]], grad_fn=<MulBackward0>)


In [106]:
# Créer un tensor w qui est la moyenne de y. Vous devrez voir la différence dans grad_fn
w = y.mean()
print(w)

tensor(0.2500, grad_fn=<MeanBackward0>)


In [107]:
# faire un backpropagation sur votre tensor w -> ce qui revient à automatiquement calculer dw/dx
w.backward()

In [108]:
# Afficher le gradient de x
print(x.grad)

tensor([[0.0625, 0.0625, 0.0625, 0.0625],
        [0.0625, 0.0625, 0.0625, 0.0625]])


In [113]:
# Effectuer une opération sur x qui n'est pas tracé dans le gradient  
t = x + 2

In [114]:
# Afficher le gradient de x (devrait rester le même)
print (x.grad)

tensor([[0.0625, 0.0625, 0.0625, 0.0625],
        [0.0625, 0.0625, 0.0625, 0.0625]])


<br> Pytorch offre également la possibilité d'effectuer les opérations des tensors sur CPU ou GPU. 

In [118]:
# Vérifier que vous avez la capacité d'exécuter sur GPU sur votre machine
torch.cuda.is_available()

False

In [ ]:
# Si vous avez GPU, vous pouvez déplacer les calculs qu'on vient de faire sur GPU
#dommage j'ai pas du GPU

<br> Vous pouvez explorer d'autres opérations torch peuvent être explorées ici: https://pytorch.org/docs/stable/torch.html

## B. Notre premier NN

![image](resources/learning.png)

Source: Deep Learning with Pytorch

<br> Dans notre TP, nous allons implémenter un feed forward NN qui identifie les chiffres écrits à la main (Hello World! des NN). La difficulté revient à identifier le même chiffre même s'il est écrit d'une manière très différente. 

Notre NN devra prendre en input une image (28 x 28 pixels) et identifier le chiffre en output. Le Dataset utilisé, __MNIST__, englobe 60.000 échantillions de chiffres écrits à la main par 250 personnes pour l'apprentissage, et 10.000 pour le test écrits par un autre groupe de 250 personnes. Les échantillons ont été rassemblés et mergés par NIST (United States' National Institute of Standards and Technology), d'où le nom du dataset. 

Pour ce faire, nous allons créer un réseau de neurones qui permet de **classfier** une image selon un **output label**. 

- Combien de Labels faudrait-il prévoir en output?

Les étapes pour la création de notre NN sont les suivants:

1. Lire et préparer les données 

2. Créer le réseau de neuronne

3. Entraîner le réseau de neuronne

4. Tester notre modèle

### 1. Lire et préparer les données

Avant d'implémenter tout modèle, il faut commencer par **Examiner et comprendre les données** puis les **formatter** convenablement pour alimenter le NN. L'objectif de cette partie est d'abord d'explorer le dataset MNIST, puis de préparer les datasets input du NN.


1.   Importer le MNIST dataset
2.   Afficher les images avec leurs labels
3.   Préparer les données: split train, test, validation et normalisation des données
4.   Créer un Pytorch Dataset

<br>

#### 1.1.   Importer le MNIST dataset

In [119]:
# importer la librairie torch et le module datasets de torchvision
import torch, torchvision

<br> Le projet torchvision contient les meilleures architectures NN pour computer vision, ainsi que des datasets standards et utilitaires pour implémenter les projest computer vision. La liste des datasets du projet peut être explorée ici: https://pytorch.org/docs/stable/torchvision/datasets.html

Le dataset MNIST contient un sous dataset pour le training et un pour le test. Récupérer ces deux sous-dataset en deux objets dataset https://pytorch.org/docs/stable/torchvision/datasets.html#mnist

N.B. Ne pas oublier de donner des noms significatifs à vos variables.
<br>

In [124]:
# Récupérer les données d'apprentissage
data = torchvision.datasets.MNIST(root='MNIST/processed/training.pt', train= True, transform: Optional[Callable] = None, 
                                  target_transform: Optional[Callable] = None, 
                                  download= False)




SyntaxError: invalid syntax (<ipython-input-124-2ccd355c3374>, line 2)

In [252]:
# Récupérer les données de test



<br> Essayons d'explorer les données dans nos datasets. MNIST devrait contenir des images de chiffres écrits à la main. Une image est représenté comme un Tensor Pytorch.

In [19]:
# Afficher un datapoint de votre dataset d'apprentissage, sa forme, le type des données, les valeurs min et max. 
# Que représente les valeurs du Tensor à votre avis?



<br></br>
#### 1.2.  Afficher les images avec leurs labels

Nous utiliserons imshow de matplotlib pour afficher un échantillon des données. Pensez à également afficher le label correspondant à chaque image en utilisant l'attribut targets votre objet MNIST dataset. 

In [260]:
import matplotlib.pyplot as plt

In [20]:
# Afficher un échantillon des images du dataset d'apprentissage avec leurs labels respectifs 


<br></br>
#### 1.3.  Préparer les données


**Créer un dataset de validation**

Notre dataset contient les données d'apprentissage et de test, nous aurons également besoin d'un dataset de validation. Pour ce faire, nous allons diviser notre dataset d'apprentissage de manière à dédier **10.000** data point à la validation. 

Nous utiliserons la librairie scikit learn qui contient une fonction permettant de diviser les données d'une manière très efficace. Pour plus de détails, voir: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

In [263]:
# Importer la fonction de splitting des données de scikit learn


In [264]:
# Créer 4 tensors en résultat du splitting: données d'apprentissage, données de validation, labels d'apprentissage, et labels de validation  



In [265]:
# Récupérer les labels de test à partir de votre sous-dataset de test



<br> Vous devez maintenant avoir 6 tensors, un pour les données et l'autre pour les labels et ce pour l'apprentissage, le test, et la validation. 

In [1]:
# Afficher la taille de chaque tensor



<br></br>
**Normaliser les données**

Il est souvent recommandé de normaliser les données avant d'alimenter le NN pour améliorer sa performance. On peut facilement redimensionner à l'intervalle [0,1] les valeurs de nos données en utilisant la moyenne et la déviation standard suivant cette formule: $$(Data - Mean) / standard Deviation$$

Comme "thumb rule", on normalise les données de test et de validation en utilisant la moyenne et la déviation des données d'apprentissage. Le raisonnement étant que les données test et validation sont indisponibles au moment de la création du NN.   

Après normalisation, le mean devrait être 0 et standard deviation à 1 (ou très proche resp. de 0 et 1).

N.B. Il faudra convertir les valeurs de vos tensors en float. 

In [316]:
# Convertir les valeurs des tensors en float


In [317]:
# Stocker dans des variables la moyenne et la déviation standard des données d'apprentissage 



In [320]:
# Normaliser les données d'apprentissage, de test, et de validation par ces valeurs




In [21]:
# Afficher la moyenne et la déviation standard de chaque dataset




<br></br>
#### 1.4. Création de Pytorch Dataset

Notre Pipeline devrait commencer par le chargement des données dans le NN. Pytorch fournit un ensemble d'outils facilitant et optimisant cette tâche. La classe **Dataset** permet de créer, sur la base de nos données, un dataset personalisé qui pourra être utilisé par la suite par la fonction built-in **DataLoader** afin d'alimenter les données lors de l'entraînement du NN. Dataset fournit un accès uniforme à nos données. DataLoader joue le rôle d'un data feeder en créant les batches de données qui fournissent au réseau de neuronne un échantillon de donnée à chaque itération.

Documentation classe Dataset: https://pytorch.org/docs/stable/data.html#torch.utils.data.Dataset

Afin de créer notre Pytorch Dataset personalisé, nous allons hériter de la classe Dataset et redéfinir les fonctions suivantes:
*   \_\_init__(self, data, targets): constructeur qui assignera les valeurs des attributs data et targets à l'objet une fois instancié
*   \_\_getitem__(self, idx) : permet de récupérer l'item à l'index idx. Utile pour éviter de charger la totalité du Dataset en mémoire (s'il est volumineux, on précise le chemin dans  \_\_init__), 
*   \_\_len__(self) : retroune la longeur de notre vecteur target

In [329]:
# Importer Dataset de torch.utils.data


In [330]:
# Créer une classe qui hérite de Dataset et redéfinit les méthodes comme susmentionné



<br> Nous allons instancier 3 objets (à partir de votre classe personnalisée) pour les données et targets de l'apprentissage, test et validation.

In [331]:
# Créer les 3 objets en instantiant votre classe





In [334]:
# Importer DataLoader de torch.utils.data



<br> DataLoader aide pour l'échantillonage et l'organisation de nos données en mini-batches. A chaque itération d'apprentissage (epoch), le DataLoader fait un shuffling des données avant de les passer au NN. DataLoader prend le dataset et la taille du batch comme argument. On mettra pour l'instant une taille de 64.   

In [335]:
# Créer une variable pour la taille du batch



In [336]:
# Créer les objets DataLoader pour vos datasets d'apprentissage, test et validation en lui donner la taille du batch convenue





In [22]:
# Quelle est la taille de vos objets dataLoader? Comment expliquer ces résultats?



<br></br>
### 2. Créer le réseau de neurones

Pytorch fournit le module nn qui comprend les classes représentant les briques de base pour construire un réseau de neurones. Il y a maintes manières de créer un NN sur Pytorch, nous allons explorer quelques unes.

In [340]:
# Importer le module nn


<br> Pytorch permet de concaténer des classes de notre choix pour la création de notre NN, et ce grâce à nn.Sequential(). Cette méthode prend les données en input, et se charge de faire passer les outputs intermédiaires aux modules suivants, puis produit l'output du dernier module.

Pour notre NN, nous allons créer une architecture composée de:

1. Input Layer: Nos images ont une taille 28 x 28. On va essayer de réduire la taille en 64
2. Fonction d'activation: ReLu
3. Hidden Layer: applique une transformation linéaire sur les données en input, et réduit leur dimension en 32
4. Fonction d'activation: ReLu
5. Output Layer: applique une transformation linéaire sur les données en input, et réduit leur dimension en 10 (Nombre de classes)

Le choix que nous venons de faire des nombres des neurones dans hidden Layer est aléatoire. 

In [343]:
# En utilisant Sequential(), créer un modèle avec l'architecture susmentionnée



In [344]:
# Afficher le nombre de paramètres qui seront entraînés par le NN créé. Pourquoi ce chiffre?



<br> Sequential est une fonction standard de Pytorch. Elle n'offre pas assez de marge de personalisation. C'est pour autant qu'on a tendance à créer nos propres classe de réseaux de neurones, en héritant de la classe nn.Module et en redéfinissant ses méthodes.

La création de notre Classe réseau de neurones se fera en héritant de nn.Module et en redéfinissant:
1. La méthode \_\_init__ où on initialise les couches à utiliser (on suivra la même architecture que le premier NN)
2. La méthode forward où on spécifie les connexions entre les couches. Cela permet de préciser les opérations qu'on appliquera sur les données à chaque passe (et leur passage de l'input, hidden, à l'output layer).


Dans la fonction forward, on utilisera le module **torch.nn.Functional** qui contient un ensemble de fonctions utiles comme les fonctions d'activation... Vous pouvez voir un exemple de définition d'un NN personalisé sur la documentation de pytorch: https://pytorch.org/tutorials/beginner/examples_nn/two_layer_net_module.html

In [350]:
# Importer torch.nn.functional



In [351]:
# Créer une classe qui hérite de nn.Module et redéfinir le constructeur ainsi que la méthode forward



In [352]:
# Instancier votre NN



In [23]:
# Vérifier que vous avez le même nombre de paramètres que le premier NN



<br></br>
### 3. Entraîner le réseau de neuronne

Maintenant que nous avons notre réseau de neurones, on devra commencer à l'entraîner. La boucle d'apprentissage est le processus qui permettra à notre réseau de neurones d'apprendre à partir des données input et d'ajuster les poids du NN selon les résultats de la fonction Loss. Pour implémenter notre boucle d'apprentissage sur Pytorch, nous avons besoin de:

1. Préciser un nombre d'itération pour l'apprentissage (epochs)
2. Définir notre fonction coût
3. Choisir l'optimiseur qui permettra d'optimiser le coût

    
Notre boucle d'apprentissage se fera selon le nombre des epochs défini, et devra comporter: 
1. Une boucle sur les données d'entraînement via DataLoader (minibatch): Alimenter les données dans le NN, Calculer le coût, et faire la backpropagation. 
2. Une boucle sur les données de validation via DataLoader:  Alimenter les données dans le NN, Calculer le coût, calculer un score de précision du modèle (on va définir un score simple qui indique le nombre de prévisions correctes).

Une bonne pratique est d'afficher les valeurs de coût et de précision pour chaque epoch.

In [356]:
# Définir la fonction du coût. On peut choisir CrossEntropyLoss



In [357]:
# Définir une fonction d'optimisation des coût: Adam par exemple. On devra définir un learning rate. On choisira 0.001.



In [358]:
# Définir le nombre d'epochs. Commencer petit. 



In [24]:
# Créer une boucle sur les epochs:
    
    # Spécifier qu'on est sur le mode entraînement
    
    # initialiser notre coût d'apprentissage à 0.0
    
    # Boucler sur les minibatchs des données d'entaînement (les données et leurs targets):
        # le vecteur des labels prédites par le modèle est le résultat de l'application du modèle sur le minibatch en cours. 
        # Nous aurons besoin d'applatir les données avant de les donner à notre NN
        
        # Calculer le coût en comparant les labels prédits aux targets du minibatch
        
        # Backpropagation: 
        # Réinitialiser l'optimiseur
        # Faire la backpropagation
        # Effectuer un pas d'optimisation

        # Mettre à jour votre coût d'apprentissage en lui ajoutant le coût du data batch
    
    # A la sortie de la boucle de l'entraînement, on calcule le coût moyen pour toutes les données training
    
    # Initiliser le coût de validation à 0.0
    
    # Initialiser le nombre de prévisions correctes à 0
    
    # Spécifier qu'on est sur le mode d'évaluation
    
    # Indiquer à Pytorch qu'on ne va pas faire de Gradient descent (comme on est dans l'évaluation)
        
        # Boucler sur les minibatchs des données de validation (les données et leurs targets):
            
            # le vecteur des labels prédites par le modèle est le résultat de l'application du modèle sur le minibatch en cours. 
            # Nous aurons besoin d'applatir les données avant de les donner à notre NN
            
            # Calculer le coût en comparant les labels prédits aux targets du minibatch
            
            # Mettre à jour votre coût de validation en lui ajoutant le coût du data batch
            
            # Mettre à jour le nombre de prévision correctes en y ajoutant le nombre des bonnes prévision sur ce batch
            # On y compare le label prédit avec le labels du minibatch. 
            # Penser à utiliser argmax pour avoir la prévision finale à partir du vecteur de prévision

        # A la sortie de cette boucle, calculer le coût moyen de validation
        
        
        # Calculer la précision: la moyenne des prévisions correctes sur l'ensemble des observations dans le dataset validation 
        

    # Afficher pour chaque itération le coût d'entraînement, le coût de validation, et la précision.
        
        

<br></br>
### 4. Tester le modèle

<br> Tester notre modèle revient à calculer la précision de la même manière que nous avons fait tout à l'heure, mais sur les données test.

In [25]:
# Initiliser le coût de test à 0.0
    
# Initialiser le nombre de prévisions correctes à 0
    
# Indiquer à Pytorch qu'on ne va pas faire de Gradient descent (comme on est dans l'évaluation)
        
    # Boucler sur les minibatchs des données de test (les données et leurs targets):
            
            # le vecteur des labels prédites par le modèle est le résultat de l'application du modèle sur le minibatch en cours. 
            # Nous aurons besoin d'applatir les données avant de les donner à notre NN
            
            # Calculer le coût en comparant les labels prédits aux targets du minibatch
            
            # Mettre à jour votre coût de test en lui ajoutant le coût du data batch
            
            # Mettre à jour le nombre de prévision correctes en y ajoutant le nombre des bonnes prévision sur ce batch
            # On y compare le label prédit avec le labels du minibatch. 
            # Penser à utiliser argmax pour avoir la prévision finale à partir du vecteur de prévision


        # A la sortie de cette boucle, calculer le coût moyen de test
        
        
        # Calculer la précision: la moyenne des prévisions correctes sur l'ensemble des observations dans le dataset test


